spring.datasource.url=jdbc:postgresql://localhost:5432/GaurdSocial
spring.datasource.username=${POSTGRES_DB_USERNAME}
spring.datasource.password=${POSTGRES_DB_PASSWORD}
server.port=${PORT:10002}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.data.redis.host=localhost
spring.data.redis.port=6379